#!/bin/bash

# brbs - beerpsi's rice bootstrapping script

# Usage: (must be run as root), inside home directory
# brbs 


# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi


# Update, install packages, no confirmation
xbps-install -Syu $(cat pkglist)

# Stow
git clone https://github.com/beerpsi/dotfiles.git
cd dotfiles/
stow *
fc-cache -f -v

echo "Done!"


